[project]
name = "digital-heritage-bastion"
authors = []
description = ""
telemetry = true
requirements = []
cache_dir = "/home/runner/workspace/digital-heritage-bastion/./.requirements"
boot_contracts = ["pox", "costs-v2", "bns"]
[contracts.digital-heritage-bastion]
path = "contracts/digital-heritage-bastion.clar"

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
